Added a pull request template
padaiyal/jPopper pull request #23
Opened 2021-01-04 16:57 UTC by the-c0d3br34k3r

Closes #20.

2021-01-05 23:05 UTC, silvs110 requested changes

2021-01-05 23:05 UTC, silvs110 commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +
Add another check for if unit tests are required and created for this PR.

2021-01-05 23:38 UTC, the-c0d3br34k3r commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +
Not needed as code coverage will not be 100% and will fail the build if it needs unit tests.

2021-01-05 23:39 UTC, the-c0d3br34k3r commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +
Nope. That'll be a separate issue.

2021-01-06 00:07 UTC, silvs110 approved these changes

2021-01-06 00:22 UTC, silvs110 approved these changes

2021-01-06 00:26 UTC, merged