Added static code analysis checks via pmd
padaiyal/jPopper pull request #24
Opened 2021-01-05 21:48 UTC by the-c0d3br34k3r

Closes #19.
The PMD maven plugin has been configured to enforce fail if any of the
following rules are violated:
 - No System.out/System.err statements.
 - No .printStackTrace() statements.
 - Default rules which can be found here:
   https://maven.apache.org/plugins/maven-pmd-plugin/examples/usingRuleSets.html

2021-01-05 23:15 UTC, silvs110 requested changes

2021-01-05 23:15 UTC, silvs110 commented on pom.xml
>                      </execution>
change version date

2021-01-06 00:12 UTC, the-c0d3br34k3r commented on pom.xml
>                      </execution>
Done in another PR.

2021-01-06 00:17 UTC, silvs110 approved these changes

2021-01-06 00:19 UTC, merged